export const productsList = [
  {
    name: "Cola",
    price: "30",
    category: "drink",
    stock: "100",
    barcode: "",
  },
  {
    name: "Wafer",
    price: "15",
    category: "food",
    stock: "100",
    barcode: "",
  },
  {
    name: "Chocolate",
    price: "25",
    category: "food",
    stock: "80",
    barcode: "",
  },
  {
    name: "Biscuits",
    price: "20",
    category: "food",
    stock: "120",
    barcode: "",
  },
  {
    name: "Lemonade",
    price: "35",
    category: "drink",
    stock: "90",
    barcode: "",
  },
  {
    name: "Apple",
    price: "10",
    category: "food",
    stock: "150",
  },
  {
    name: "Orange Juice",
    price: "40",
    category: "drink",
    stock: "70",
  },
  {
    name: "Banana",
    price: "12",
    category: "food",
    stock: "130",
  },
  {
    name: "Milk",
    price: "28",
    category: "drink",
    stock: "110",
  },
  {
    name: "Cheese",
    price: "50",
    category: "food",
    stock: "60",
  },
  {
    name: "Coca Cola",
    price: "35",
    category: "drink",
    stock: "95",
  },
  {
    name: "Sandwich",
    price: "45",
    category: "food",
    stock: "75",
  },
  {
    name: "Sprite",
    price: "32",
    category: "drink",
    stock: "85",
  },
  {
    name: "Pizza",
    price: "55",
    category: "food",
    stock: "50",
  },
  {
    name: "Tea",
    price: "18",
    category: "drink",
    stock: "125",
  },
  {
    name: "Coffee",
    price: "22",
    category: "drink",
    stock: "105",
  },
  {
    name: "Chicken Burger",
    price: "48",
    category: "food",
    stock: "65",
  },
  {
    name: "French Fries",
    price: "27",
    category: "food",
    stock: "140",
  },
  {
    name: "Ice Cream",
    price: "60",
    category: "food",
    stock: "55",
  },
  {
    name: "Mineral Water",
    price: "38",
    category: "drink",
    stock: "80",
  },
  {
    name: "Cigarette",
    price: "38",
    category: "smoke",
    stock: "80",
    barcode: "86940573",
  },
];
